### ISSUE TITLE
Add Keen F(Q) in CLI errors on length of DataFrame

### ISSUE THREAD

**Issue by marshallmcdonnell** [neutrons/pystog#34]
Getting this error when I run the files attached below:

```
loading config from './data/examples/base_1_pystog.json'
Traceback (most recent call last):
  File "/home/ntm/.local/share/virtualenvs/pystog-_b47w3aQ/bin/pystog_cli", line 11, in <module>
    load_entry_point('pystog', 'console_scripts', 'pystog_cli')()
  File "/home/ntm/direnv/python3/pystog/pystog/cli.py", line 57, in pystog_cli
    stog._add_keen_fq(q, sq)
  File "/home/ntm/direnv/python3/pystog/pystog/stog.py", line 1238, in _add_keen_fq
    q, fq, self.df_sq_master, self.fq_title)
  File "/home/ntm/direnv/python3/pystog/pystog/stog.py", line 1436, in add_to_dataframe
    df = pd.concat([df, df_temp], axis=1)
  File "/home/ntm/.local/share/virtualenvs/pystog-_b47w3aQ/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 229, in concat
    return op.get_result()
  File "/home/ntm/.local/share/virtualenvs/pystog-_b47w3aQ/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 426, in get_result
    copy=self.copy)
  File "/home/ntm/.local/share/virtualenvs/pystog-_b47w3aQ/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 2065, in concatenate_block_managers
    return BlockManager(blocks, axes)
  File "/home/ntm/.local/share/virtualenvs/pystog-_b47w3aQ/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 114, in __init__
    self._verify_integrity()
  File "/home/ntm/.local/share/virtualenvs/pystog-_b47w3aQ/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 311, in _verify_integrity
    construction_error(tot_items, block.shape[1:], self.axes)
  File "/home/ntm/.local/share/virtualenvs/pystog-_b47w3aQ/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 1691, in construction_error
    passed, implied))
ValueError: Shape of passed values is (3164, 3), indices imply (3140, 3)
```

**Comment by marshallmcdonnell** [comment]
```
